### ISSUE TITLE
FAQ page frontend

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#104]
![image](https://user-images.githubusercontent.com/50821962/172077004-b5f4c499-81bc-45e7-a2ad-46eb08c71fbc.png)
See Figma

- [ ] FAQ page header and search bar
- [ ] Button selector implementation #86 
- [ ] Question accordions #31 
- [ ] New question input and submit

**Comment by Cali0707** [comment]
@lukewarmtemp any updates on the status of this?
