### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#106]
![image](https://user-images.githubusercontent.com/50821962/172077146-984ccbd4-a2b0-411d-b75f-e693614e7e4b.png)
See Figma

- [x] See form components: #33 #32 #34 
- [x] Follow plan laid out by Registration Subcom (awaiting details)

**Comment by jameskokoska** [comment]
https://docs.google.com/spreadsheets/d/1AsUlf4bCz3RTH8bkUI_go9HUOviN-QwMLLJhqBffTPY/edit#gid=1257541486

**Comment by MatthewGWilson** [comment]
Hey Emily, reach out to me when you can so we can talk some details about this page and so I can get you all the information you need to set it up

**Comment by jameskokoska** [comment]
Hi Matt, I have taken over this ticket for now
I was going through last years code, it seems like there is more to this form than I thought

**Comment by jameskokoska** [comment]
https://github.com/UofT-Frosh-Orientation/orientation-website/pull/123

**Comment by jameskokoska** [comment]
4fd901d81bf1f5bb0b711abc583a94a535986717

**Comment by jameskokoska** [comment]
Basic form layout and fields

Next:
- [ ] validation
- [ ] dependencies
- [ ] frosh object creation
- [ ] backend integration
- [ ] tabbed layout (see https://github.com/UofT-Frosh-Orientation/orientation-website/issues/87)
