### ISSUE TITLE
Highlight current page in navbar

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#159]
For e.g. if on Home page, keep it underlined

**Comment by jameskokoska** [comment]
@natapokie This will tell you what page you currently are on https://v5.reactrouter.com/web/api/Hooks/uselocation

**Comment by natapokie** [comment]
> @natapokie This will tell you what page you currently are on https://v5.reactrouter.com/web/api/Hooks/uselocation

Thank you!!

**Comment by natapokie** [comment]
Note to self: while working on navbar and footer, don't forget to update z-indices!

- [ ] update z-indices!!! `z-index: 100` for containers
