### ISSUE TITLE
Profile page resources

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#185]
![image](https://user-images.githubusercontent.com/50821962/174924206-f4125ea4-1a66-46cc-8c88-f96cdb4f4977.png)
They do nothing, as of now

**Comment by jameskokoska** [comment]
Need a list @MatthewGWilson

**Comment by MatthewGWilson** [comment]
I'm going to get Frosh Relations on this and it should done soon

**Comment by jameskokoska** [comment]
They/or you can leave a comment on this issue with a list and links 
and whoever grabs this ticket can implement it 

ideally we have backend implementation of this so it can be edited from an admin panel, but this will be future quality of life improvements

**Comment by Cali0707** [comment]
@jameskokoska can we add some sort of "Coming soon..." here, perhaps a popup until we have the resources? I agree that this should ideally be a backend thing, I'll open a ticket to implement that

**Comment by MatthewGWilson** [comment]
Here's a list of a few for now, let me know if you need more info than this https://docs.google.com/spreadsheets/d/1Ff_bvdcNbfnbWc-Brm6xqCROWpRyT8gDBA-Kbm734lQ/edit#gid=0
