### ISSUE TITLE
About page image 

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#200]
![image](https://user-images.githubusercontent.com/50821962/175358010-7a99cbb7-0667-4c19-8253-bdecf9dec728.png)

Don't know how this happened, but could someone take a look?

**Comment by jameskokoska** [comment]
Oh it's because it's the same color as the background
I'll fix

**Comment by natapokie** [comment]
@jameskokoska i was going to swap the logo since the bg colour was the same, but i was too slow 😂 you already fixed it 😂

**Comment by jameskokoska** [comment]
You can still swap if you want don't worry, just make a new branch and submit PR

**Comment by natapokie** [comment]
> You can still swap if you want don't worry, just make a new branch and submit PR

Sounds good! Although i just realized the other logo i had in mind has not been finished yet 😅😅
