### ISSUE TITLE
Fix the website icon and share info

### ISSUE THREAD

**Issue by Cali0707** [UofT-Frosh-Orientation/orientation-website#203]
The icon for the website in the browser (as well as all the info that normally shows up for websites when you share them) should be populated with the correct info. See below for the current info being displayed
![IMG_2243](https://user-images.githubusercontent.com/65566908/175791100-d842c46c-fb58-4fdd-9a47-128d86644b25.jpg)

@MatthewGWilson any ideas on what we should have for the title of the website/the short description/the preview image? I'm assuming that the icon for the website in the browser should just be the orientation logo

**Comment by MatthewGWilson** [comment]
Orientation logo makes sense for the preview image (in the brandbook https://docs.google.com/document/d/17LKk0AxolWOlmnJ4XCLkCdVXNj24itCFuAKYZT9byWw/edit), title of the site should just be "F!rosh Week 2T2", short description can be "University of Toronto Engineering Orientation Week 2T2"
