### ISSUE TITLE
Copy for emails

### ISSUE THREAD

**Issue by Cali0707** [UofT-Frosh-Orientation/orientation-website#219]
We need copy for three emails ahead of launch: password reset, signup confirmation, and registration confirmation.

The definition of done for this is:
- [ ] Text and variables to be replaced in the text for the password reset email
- [ ] Text and variables to be replaced in the text for the signup confirmation email
- [ ] Text and variables to be replaced in the text for the registration confirmation email

Optionally, it would be great if the html version of these emails was also provided

**Comment by MatthewGWilson** [comment]
[Registration Confirmation.zip](https://github.com/UofT-Frosh-Orientation/orientation-website/files/9051162/Registration.Confirmation.zip)
[Signup Confirmation.zip](https://github.com/UofT-Frosh-Orientation/orientation-website/files/9051163/Signup.Confirmation.zip)
[Password Reset.zip](https://github.com/UofT-Frosh-Orientation/orientation-website/files/9051164/Password.Reset.zip)

Only thing I wasn't sure about was the password reset email where I assume we'll have to insert a url for the site they go to to actually reset the email, let me know if there's anything special I have to do to set it up for that

**Comment by Cali0707** [comment]
@Freeassassin see the message from matthew above

**Comment by Cali0707** [comment]
Thanks @MatthewGWilson looks good!!
