### ISSUE TITLE
Populate timeline with dates and info

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#231]
Dates, info, description, links
- [x] Need info from @MatthewGWilson 
- [x] Then someone add to timeline

Timeline just has filler info right now...

**Comment by MatthewGWilson** [comment]
Not much to add yet but these can be the starter events for the timeline https://docs.google.com/spreadsheets/d/1USJ991YWT9iQ-1aRyTcO4q_P_rEw5_E9yTk9cX8_PS0/edit#gid=0 If there are new events to add I'll create a new sheet

**Comment by NeoLou** [comment]
Timeline events added to database
