### ISSUE TITLE
Faq page "Ask a Question" Pop Up Burry on Mobile

### ISSUE THREAD

**Issue by lukewarmtemp** [UofT-Frosh-Orientation/orientation-website#284]
Mobile:
![image](https://user-images.githubusercontent.com/74154406/178628113-09a1d78d-1906-4f6d-a41f-70d13d333359.png)

When changing to mobile view on chrome, there seems to be a slight blur applied on top of the pop-up as well instead of just the background.

Desktop for comparison:
![image](https://user-images.githubusercontent.com/74154406/178628419-0170f403-0e94-4092-a166-308912bc9a20.png)

**Comment by jameskokoska** [comment]
It's an optical illusion, it's actually just a white shadow
