### ISSUE TITLE
[Bug]: Typo in VCI Bio

### ISSUE THREAD

**Issue by MatthewGWilson** [UofT-Frosh-Orientation/orientation-website#295]
### Describe the bug

At the end of the My Role section there's a extra ' and ,

### How To Reproduce

1. Go to About Page
2. Click on VCI to view bio information

### Expected behavior

I expected it to not have a typo lol

### What device were you using when you encountered the error?

Dell XPS 8940

### What browser were you using when you encountered the error?

Chrome

### What operating system were you using?

Windows 10

### Additional Information

Idk if it was a typo I left in there or it got added when it copied was over. Sorry though!

**Comment by jameskokoska** [comment]
Fixed by https://github.com/UofT-Frosh-Orientation/orientation-website/commit/f6ca193ddebe5f81bf8e161237d2ef0678cc71d3
