### ISSUE TITLE
[Bug]: Just a few typos / text additions

### ISSUE THREAD

**Issue by kerrynvanrooyen** [UofT-Frosh-Orientation/orientation-website#296]
### Describe the bug

There are just a few spots I would like the text to be changed, one in About Us and two event descriptions on the home page. 

### How To Reproduce

1. Go to the About Us Page
2. There is an extra ' at the start of the first paragraph
*******
1. Go to the home page 
2. Click the Tuesday on the schedule 
3. Can we add into the blurb that describes e4tw that it stands for 'Engineers For The World' please? It currently says:
"E4TW: Your first design challenge at UofT Engineering, except it’s probably the best one you'll do" but instead could it be:
"E4TW (Engineers 4 The World) is your very first design challenge here at U of T Engineering!"

### Expected behavior

This format doesn't really make sense for this issue I just want the text fixed lol 

### What device were you using when you encountered the error?

MacBook Pro

### What browser were you using when you encountered the error?

Safari

### What operating system were you using?

macOS Monterey

**Comment by jameskokoska** [comment]
Fixed by https://github.com/UofT-Frosh-Orientation/orientation-website/commit/f6ca193ddebe5f81bf8e161237d2ef0678cc71d3
