### ISSUE TITLE
[Bug]: Site crashes if you create an account, don't fill out registration, go to the profile page and attempt to edit your registration information

### ISSUE THREAD

**Issue by MatthewGWilson** [UofT-Frosh-Orientation/orientation-website#297]
### Describe the bug

Site crashed when attempting to edit registration info without filling out any registration info

### How To Reproduce

1. From main site select login and create an account
2. Select register from the popup after creating an account
3. Don't fill in any information for registration
4. Go to frosh profile by selecting the button in the top right
5. Select the yellow edit button in the top right

### Expected behavior

I expected to be able to edit registration information by selecting the edit button

### What device were you using when you encountered the error?

Dell XPS 8940

### What browser were you using when you encountered the error?

Chrome

### What operating system were you using?

Windows 10

**Comment by MatthewGWilson** [comment]
Ah thanks I didn't see you already caught this one!

**Comment by Cali0707** [comment]
Resolved by #301
