### ISSUE TITLE
Form page for adding and modifying timeline events

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#299]
So higher permission users can add timeline events to the backend
Doesn't need to look that pretty

**Comment by NeoLou** [comment]
Should this be a separate page? If yes should I add a button somewhere on the profile page of higher permission users?

**Comment by jameskokoska** [comment]
Should be a separate page. Technically doesn't matter but up to you
Yea you can add it in the resource section if you want. Usually we just give the subcoms the direct link since they only work with one area of the website usually
