### ISSUE TITLE
Popup modal component

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#30]
From last year:

ContainerPopupModal
A popup container that can hold components
header: string (optional)
children: components
accessible functions via ref: ref.setModalState(boolean)
exitButton: boolean (default: true)
exitBackground: boolean (default: true) - will exit the modal if the blurred background is clicked
blurBackground: boolean (default: true)
customPosition: CSS className (default: none) - will allow you to use absolute positioning (also specify width and height)
smallInfoModal: boolean (default: false) - will create a small popup with info, if clicked anywhere it will close (NOTE: customPosition must be true)
onStateChange: function(boolean) - (optional) will run when the modal is open/closed

ContainerPopupModalConfirm wraps from ContainerPopupModal
Modal with 2 options
labelYes: string (optional) - default: Yes
labelNo: string (optional) - default: No
buttonCallback: function(boolean) - returns true if Yes, false if No;
accessible functions via ref: ref.setModalState(boolean)

![image](https://user-images.githubusercontent.com/50821962/168833394-633e46c7-501b-439c-91f6-728171fc265d.png)
![image](https://user-images.githubusercontent.com/50821962/168833420-c943ec6b-6f07-4a29-b0e8-35cbf8414ad3.png)

**Comment by natapokie** [comment]
Two variations for popups, depending on background colour

(1)
![Text Pop Up_dark](https://user-images.githubusercontent.com/86009011/169069568-dedc17fa-385a-466c-9be3-6eb0f3f0cd2d.png)
(2)
![Text Pop Up_light](https://user-images.githubusercontent.com/86009011/169069587-1df95a75-6ed9-4cd1-bf2a-b6793324f58a.png)

- box  
  - Fill: Solid (1) #B297C7 | (2) #ECD6FF
  - Corner radius: 12px
- drop shadow
  - Effect: Drop shadow
  - Radius: 20px
  - Offset: 0px, 0px
  - rgba(0, 0, 0, 0.4)

**Comment by natapokie** [comment]
> @natapokie is this included in your recent PR?

Yep! Just need to fix it up a little more
