### ISSUE TITLE
[Bug]: Creating an account with an already used email

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#303]
### Describe the bug

If you try to create an account with an email that was already used, it doesn't show the error. It just returns an error in console, but should return a proper error message to the user.

### How To Reproduce

Try to create an account with an already used email

### Expected behavior

Should show an error message to the user

### What device were you using when you encountered the error?

Laptop

### What browser were you using when you encountered the error?

Chrome

### What operating system were you using?

Windows 10

**Comment by Cali0707** [comment]
@jameskokoska I can fix this tomorrow

**Comment by jameskokoska** [comment]
Fixed
