### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by christineMar3** [UofT-Frosh-Orientation/orientation-website#305]
### Describe the bug

The schedule says Scunt/Nitelife and gives a description of both but only Scunt will be running that evening.

### How To Reproduce

1. Home page
2. Scroll to schedule
3. click 'Wednesday'
4. click 'Havenger Scunt/Nitelife'

### Expected behavior

Only listing Havenger Scunt for the evening events

### What device were you using when you encountered the error?

Macbook

### What browser were you using when you encountered the error?

Chrome

### What operating system were you using?

macOS monterey

**Comment by natapokie** [comment]
only Havenger Scunt listed in evening events for wednesday (on Home page schedule and profile page schedule)!
![image](https://user-images.githubusercontent.com/86009011/179340174-4be73188-83e4-428d-9a21-dbb2ebaac374.png)
