### ISSUE TITLE
Other pronoun field not working[Bug]: 

### ISSUE THREAD

**Issue by jordangreenberg** [UofT-Frosh-Orientation/orientation-website#307]
### Describe the bug

Can't set other pronoun

### How To Reproduce

1. Go to registration page
2. Put in legal name
3. Put in pronoun
4. Try to select other pronoun

### Expected behavior

Setting other pronoun

### What device were you using when you encountered the error?

Windows 10 laptop

### What browser were you using when you encountered the error?

Google Chrome

### What operating system were you using?

Windows 10

**Comment by Cali0707** [comment]
I'm unable to recreate this. @UofT-Frosh-Orientation/tech-team-2t2 can anyone recreate this?

**Comment by natapokie** [comment]
> I'm unable to recreate this. @UofT-Frosh-Orientation/tech-team-2t2 can anyone recreate this?

nope, I can't either, I'm on windows 10 too 🤔

**Comment by jordangreenberg** [comment]
Oh whoops, I tried again and then I realized you need to select "Other" in the dropdown for the text field beside it to activate. Sorry about that!

**Comment by Cali0707** [comment]
No worries! Glad this is resolved
