### ISSUE TITLE
From checkbox component

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#32]
From last year:

label: string
option: string
disabled: boolean (default: false)
required: boolean (default: false)
onChange: function(text)
default: boolean (default:false)
small: boolean (default:false) (specifies font size)
localStorageKey: string - if not undefined, it will save the selected value to storage
accessible functions via ref: ref.getValue
![image](https://user-images.githubusercontent.com/50821962/168833899-96733d97-ea23-4fa7-a3ed-4452605fb3ad.png)

**Comment by natapokie** [comment]
![Form Checkbox](https://user-images.githubusercontent.com/86009011/169072219-acb0df29-5c70-4b81-b068-04f2a46ec651.png)

- unchecked
  - background: #FFFFFF;
  - border: 2px solid #621790;
  - border-radius: 5px; (inside alignment for border)
- checked (variations depending on bg colour)
  - fill - yellow: #FFE76A | purple: #621790
- disabled
  -  grey: #989898
