### ISSUE TITLE
(draft) Form page for modifying schedules

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#324]
```
Create a page for higher end users so that they can edit/add events for each individual frosh group
This page can also be used to edit/create events on the home page

https://github.com/UofT-Frosh-Orientation/orientation-website/blob/dev/client/src/assets/schedule/data.jsx
```

## **Changes:**

Describe the visual changed required.

## **Visuals:**

Any visuals that are related to these changes

## **Requirements:**

- [ ] todo 1
- [ ] todo 2
- [ ] todo 3

## **External Factors:**

Describe any external requirements that might effect the issue (e.g need to await information from other party).

## **Related Issues/PRs:**

Link any other issue or PR that might be related to this issue.
- #94 

## **Resources:**

Link any resources or people that might be helpful in the accomplishment of the issue.

### **Tutorials:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

### **Documentation:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

**Comment by jameskokoska** [comment]
Use a package and visuals to make it easy to create events?
Or you can just use generic text input for now

**Comment by natapokie** [comment]
no longer applicable for this year
