### ISSUE TITLE
Form radio buttons

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#33]
From last year:

Radio button
label: string
options: list of strings
disabledIndex: list of numbers
allDisabled: boolean
required: boolean (default: false)
onChange: function(text)
setValue: function(value:string) DOES NOT RUN onChange!
defaultIndex: integer (default: 0)
small: boolean (default:false) (specifies font size)
localStorageKey: string - if not undefined, it will save the selected value to storage
accessible functions via ref: ref.getValue

![image](https://user-images.githubusercontent.com/50821962/168834040-3efa1300-c810-4449-96a5-707d569404e2.png)

**Comment by natapokie** [comment]
![Form Radio Components](https://user-images.githubusercontent.com/86009011/169073733-2fec8dc8-75ef-41c6-82f6-37bd8a161f8f.png)

- not disabled
  - purple #621790
  - outline - Align: Inside, Width: 2px 
- disabled
  - grey #989898
  - same outline as purple ones
