### ISSUE TITLE
Text box input component

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#34]
Code can be looked at, cleaned up, and ported from last year

From last year:

Form text box and text area
type: string (textArea, text, date...)
label: string
styleClass: CSS className (default: none)
style: styles (optional)
small: boolean (default:false)
margin: boolean (optional) (default: true) - adds vertical spacing
description: string (optional) - info popped up when hovered
required: boolean (default: false)
error: string (optional)
disabled: boolean (default:false)
defaultValue: string (optional)
onChange: function(text) (optional)
onEnterKey: function() (optional) - not supported for textarea type
clearButton: boolean (default: false)
localStorageKey: string - if not undefined, it will save the selected value to storage
accessible functions via ref: ref.getValue

![image](https://user-images.githubusercontent.com/50821962/168834161-8e1993a9-d2b3-4d6d-b1c6-6c6d61f2bcfa.png)

**Comment by natapokie** [comment]
![Text Box Input](https://user-images.githubusercontent.com/86009011/169074299-21266fd7-ef83-4fd8-a569-7622debc6ef5.png)

- boxes
  - outline: #B297C7
  - Corner radius: 6px
- active text boxes (i.e. clicking on it/typing into it) 
  - 2px border (inside alignment)
- non active text boxes 
  - 1px border (inside alignment)
- error
  - red #FF2532
  - 2px border (inside alignment)
  - asterisk svg ([https://fontawesome.com/icons/asterisk?s=solid](https://fontawesome.com/icons/asterisk?s=solid))
- scrollable option for long response text box
  - scroll clicking part #B297C7
  - not the scrolling part #ECD6FF
- disabled
  - Stroke: Solid #6C6C6C
  - Fill: Solid #EBEBEB
  - text: #989898
