### ISSUE TITLE
[Bug]: Can't pay for F!rosh Week

### ISSUE THREAD

**Issue by VectorBolt** [UofT-Frosh-Orientation/orientation-website#343]
### Describe the bug

When I click "Pay Now" on the registration page, the website just takes me back to the beginning of the form, despite everything being filled out.

### How To Reproduce

1. Create account 
2. Go to home page
3. Click "Register"
4. Fill out information
5. Click "Pay Now" on the last page

### Expected behavior

I expected to be taken to a payment portal to enter in credit/debit card information.

### What device were you using when you encountered the error?

Macbook Air (Intel)

### What browser were you using when you encountered the error?

Safari and Chrome

### What operating system were you using?

MacOS Catalina 10.15.7

**Comment by jameskokoska** [comment]
Fixed via https://github.com/UofT-Frosh-Orientation/orientation-website/commit/48adcf6fddb7cc3bef79f20b542ab8843e282b65
