### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#36]
From last year:

A button with onClick
label: string
onClick: function
primary: boolean (default: true)
disabled: boolean (default: false)
large: boolean (default: false)
![image](https://user-images.githubusercontent.com/50821962/168834723-9eb1a8c9-5033-428a-a41a-6b87e773cfea.png)

Another type of button:
label: string
onClick: function
link: link location (string)
accent: true
![image](https://user-images.githubusercontent.com/50821962/168834796-c8ddf57d-8e0f-4cb1-aedc-eb3abe88ef94.png)

**Comment by natapokie** [comment]
onClick Button
![Button onClick](https://user-images.githubusercontent.com/86009011/169082677-958132c2-d707-4ecf-9fcd-9fec981c679a.png)
- unpressed (default)
  - outline: #B297C7, inside alignment, 2px stoke width
- pressed
  - outline: #621790, inside alignment, 2px stoke width
  - drop shadow: 
    - Radius: 20px
    - Offset: 0px, 0px
    - rgba(0, 0, 0, 0.25)
- disabled
  - Fill: Solid #EBEBEB 
  - Stroke: Solid #6C6C6C
    - Align: Inside
    - Width: 2px  
  - text: #989898

Bubble Button
![Button Bubble (1)](https://user-images.githubusercontent.com/86009011/169082674-c5956f16-dc57-4fcc-b426-a3de5f6f1b21.png)
- pressed
  - Stroke: Solid #621790
    - Align: Mixed
    - Width: 2px
  - Fill: Solid #B297C7
- unpressed
  - Stroke: Solid #B297C7
    - Align: Inside
    - Width: 2px
  - Fill: Solid #ECD6FF
