### ISSUE TITLE
Sponsors Information

### ISSUE THREAD

**Issue by MatthewGWilson** [UofT-Frosh-Orientation/orientation-website#362]
All information for the sponsors is here: https://docs.google.com/spreadsheets/d/1hRix3Bzhyk0kUzs67i0spGW6FomEWNvQO97ne5tcD2M/edit?usp=sharing

For different levels of sponsors we're not exactly sure how we want to show the difference. We definitely want higher level sponsors closer to the front and center where they're more visible. We are thinking it might be nice to have titles e.g. Gold Level Sponsor: Neo but I'm open to other ideas (maybe a gold, silver, or bronze outline on the logo?).

**Comment by jameskokoska** [comment]
Sounds good. Usually when they get sponsors for Frosh week, they get some perks on the website. Wondering if something was promised.

**Comment by jameskokoska** [comment]
Done, if you want more sponsors added please create a new issue
Also, I changed the sponsor images to a higher quality. Let me know if it needs to be changed back to the original ones you provided
