### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#38]
From last year:

A tool tip text that pops up when the component passed in is hovered
description: string
placement: string (default: bottom)

children: component
OR
width: string (size)
style: styles

![image](https://user-images.githubusercontent.com/50821962/168835345-7d042ae2-3780-4c7d-8b34-91de318b407d.png)

**Comment by natapokie** [comment]
Information Icon Tool Tip
![Tool Tip 1](https://user-images.githubusercontent.com/86009011/169084986-9578bff7-b69e-44db-949d-0463db78b399.png)
- Fill #621790
- Corner Rounding: 12px
- info icon ([https://fontawesome.com/icons/circle-info?s=solid](https://fontawesome.com/icons/circle-info?s=solid))

Mouse Follower Tool Tip on Hover
![Tool Tip 2](https://user-images.githubusercontent.com/86009011/169084989-d6bbbce0-d614-404b-93aa-f4a5d9bacc23.png)
- Fill #621790
- placement: centred on mouse coordinated
-  Corner Rounding: 100px+ (as round as possible)
