### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#40]
This year design:
![image](https://user-images.githubusercontent.com/50821962/168836064-9b1107c1-0f7a-49f3-8add-bf892ed19a0a.png)

Last year:
source in client/components/footer.js
![image](https://user-images.githubusercontent.com/50821962/168835924-c52dc317-3802-430a-9675-cb4d7c9ef6f0.png)

**Comment by Cali0707** [comment]
Just do the layout, ignore the background
