### ISSUE TITLE
Text components

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#41]
This year design:
Refer to figma

Last year:
![image](https://user-images.githubusercontent.com/50821962/168837197-a23f12be-8ed0-4248-977f-c7f232763d00.png)
![image](https://user-images.githubusercontent.com/50821962/168837225-a795b840-3ec1-41d2-9b66-cf68c919fa2e.png)
![image](https://user-images.githubusercontent.com/50821962/168837239-a28c2ff8-2298-4339-ac52-05c8956db7d8.png)
![image](https://user-images.githubusercontent.com/50821962/168837254-aaeaf24a-8f2a-40fc-8647-0a7bfe849e13.png)
![image](https://user-images.githubusercontent.com/50821962/168837276-92d561b2-831a-4ce5-a805-e0a5cf9e586b.png)
![image](https://user-images.githubusercontent.com/50821962/168837296-42c8d716-f2e4-45b7-9596-44b9aaff5526.png)
![image](https://user-images.githubusercontent.com/50821962/168837317-42bef31f-34b5-473e-b4b2-db73b3fbe763.png)
![image](https://user-images.githubusercontent.com/50821962/168837338-68c01bb8-ef61-410c-be61-2879a554a08c.png)

**Comment by Cali0707** [comment]
@jameskokoska these are already all in the new codebase - I reused them from last year. If you want to re-design any of them feel free to re open this : )

**Comment by jameskokoska** [comment]
Ya going to redesign
To follow the website better and follow better practices
I should do this before we start making the pages
