### ISSUE TITLE
Update About Us Page with Subcom and HL info

### ISSUE THREAD

**Issue by natapokie** [UofT-Frosh-Orientation/orientation-website#424]
@natapokie Apologies for the delay, here's the info for all the HLs and Subcoms https://docs.google.com/spreadsheets/d/1SkuHRKWlmUajmTbHV2Vw-a5zKMQ9CIbpkVSJZcY4CHQ/edit?usp=sharing

_Originally posted by @MatthewGWilson in https://github.com/UofT-Frosh-Orientation/orientation-website/issues/311#issuecomment-1199942648_

**Comment by jameskokoska** [comment]
https://drive.google.com/drive/folders/1q5PI6ZdgTn4E2kvbEcguCQNiNMiMBDf5

subcom profile images
