### ISSUE TITLE
FAQ admin page should update the list when item is deleted

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#472]

**Comment by lukewarmtemp** [comment]
@jameskokoska do you mind giving me a few more details on the issue? I've tested deleted questions on the faq admin page it immediately deletes removes the question from the faq admin page, marks them as deleted in the database, and removes it from the public faq admin page.

**Comment by jameskokoska** [comment]
Looks like it has been fixed!
