### ISSUE TITLE
[Bug]: The FAQ page always shows no result

### ISSUE THREAD

**Issue by pandyah5** [UofT-Frosh-Orientation/orientation-website#491]
### Describe the bug

The FAQ page produces "no results" for most/all searches

### How To Reproduce

1) Go to https://beta.orientation.skule.ca/faq
2) Type UofT OR frosh OR Toronto in the search bar

It produces "no result". The above three words are most common hence I used them. You can try other words too. **An autofill feature would also help very much.**

### Expected behavior

I expect to see some results for common words

### What device were you using when you encountered the error?

Asus ROG laptop

### What browser were you using when you encountered the error?

Chrome Browser

### What operating system were you using?

Windows 11

**Comment by jameskokoska** [comment]
Hi, please use the official website as the beta does not have populated information
You can find it here: https://orientation.skule.ca/faq

Closing this issue
