### ISSUE TITLE
Ability to delete accounts

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#498]
- [ ] Add new scope for deleting accounts to frontend 
- [ ] Add new account delete route (with user id)
- [ ] Add delete column to frosh data table page with X icon and functionality to frontend (and if correct auth scopes)
Tip: Create a new column on the right most (to avoid accidental presses) similar to how the '#' column is created (it is not part of the users object, it is just a custom column with a count)
- [ ] Add delete confirmation popup on frontend before proceeding

**Comment by NeoLou** [comment]
How would you access the accounts that are not fully registered and the leader accounts since they won't be on the frosh data table page?

**Comment by jameskokoska** [comment]
> How would you access the accounts that are not fully registered and the leader accounts since they won't be on the frosh data table page?

If you have the correct auth scopes it's possible to see all users (paid, not paid, leaders)
if you have permission to delete accounts - you will only have permission to delete the accounts that appear on that page (unless you run the route manually) 
anyone with the delete route permission can delete any user (to keep it simple) given a user ID
