### ISSUE TITLE
Auth Scope request page formatting

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#502]
Instead of a long vertical list
![image](https://user-images.githubusercontent.com/50821962/185539489-71195c74-8142-447c-b105-ec5b2ddb40c6.png)

maybe something similar to below would be a better use of space (flex box?)
![image](https://user-images.githubusercontent.com/50821962/185539685-76e0496e-8233-4bea-aeee-4cf6e9be4240.png)

**Comment by natapokie** [comment]
no longer using auth page
