### ISSUE TITLE
Update Email Blurbs

### ISSUE THREAD

**Issue by natapokie** [UofT-Frosh-Orientation/orientation-website#662]
## **Changes:**

Describe the visual changed required.

## **Visuals:**

Any visuals that are related to these changes

## **Requirements:**

- [ ] Update email blurbs to the ones from joanna
- [ ] Update any instance of 2T2 to 2T3 in email blrubs
- [ ] Add header images and footer social links (or whatever design Aidan sends)

## **External Factors:**

Describe any external requirements that might effect the issue (e.g need to await information from other party).

See blurb below for registration confirmation email,

> Hi [Name],
> 
> Thank you for registering for F!rosh Week 2T3!!!
> Please find attached your information PDF which includes a receipt of your data and your unique QR code that you will use for a variety of activities during F!rosh Week.
> 
> We look forward to seeing you soon!
> 
> To keep up to date with all the info you need to know before you arrive here for orientation, and to learn more about our meetup events running over the summer make sure to follow our Instagram page @froshweek or check us out on our other social media platforms. 
> 
> If you have any questions or want to learn more feel free to email us at orientation@skule.ca!
> 
> With HYPE,
> F!rosh Week Orientation Committee

## **Related Issues/PRs:**

Link any other issue or PR that might be related to this issue.

## **Resources:**

Link any resources or people that might be helpful in the accomplishment of the issue.

### **Tutorials:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

### **Documentation:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

**Comment by Freeassassin** [comment]
Addressed in #644
