### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by avacadoo05** [UofT-Frosh-Orientation/orientation-website#678]
### Describe the bug

Im not able to pay :(

### How To Reproduce

I started y profile last night and now I can’t do the payment part
The rest of my information was saved though
Do I have to make a new account?

### Expected behavior

The payment page would open/load

### What device were you using when you encountered the error?

iPhone 8

### What browser were you using when you encountered the error?

Safari

### What operating system were you using?

iOS 16.5.1

**Comment by natapokie** [comment]
@avacadoo05 
Hi, thanks for sending a report, we're a little confused about the bug you're facing...
From what it sounds like, there is probably an error in one of the fields you've entered, can you try refreshing the page and rechecking the fields?

**Comment by avacadoo05** [comment]
All my fields were filled out, and I had refreshed multiple times
It’s okay thought now, I tried doing it on my computer instead and it worked fine!

**Comment by natapokie** [comment]
@avacadoo05 
ok sounds great! We've been going through some updates to correct any issues we had with certain fields, so even though you refreshed the browser, it might've not updated :)
thanks for registering for frosh week 💜 !
