### ISSUE TITLE
New admin privileges system

### ISSUE THREAD

**Issue by Freeassassin** [UofT-Frosh-Orientation/orientation-website#681]
## **Changes:**

Create a new page to grant admin access to certain accounts. This will be similar to the page we currently have set up for users to request admin access, [client/src/pages/ScopeRequest](https://github.com/UofT-Frosh-Orientation/orientation-website/tree/dev/client/src/pages/ScopeRequest).

(tbd, details may be changed)
- will need some sort of input field to select the user you want to grant access to (will need to check with this)
- will need a button to grant privileges, this button should then open a popup to confirm these changes
- there will be five-tier systems of permission scopes, see the link [here](https://docs.google.com/spreadsheets/d/1OUqBWF5s8c8qeTb987YN9kJGvo1hbiQ9_VqEjaT4BtQ/edit?usp=sharing)
  - all tiers will be regarding frosh data, you can take a look at this function, `getTotalRegistrationScopes`, in this file, [client/src/pages/ScopeRequest/functions.jsx](https://github.com/UofT-Frosh-Orientation/orientation-website/blob/dev/client/src/pages/ScopeRequest/functions.jsx)
  - e.g., emails in tier 1 will be given access to all frosh registration scopes
- similar to the ScopeRequest page, make sure to add the new page to [pages.jsx](https://github.com/UofT-Frosh-Orientation/orientation-website/blob/dev/client/src/util/pages.jsx), 
  - make sure that the new page has the `<AuthorizedPage leaderOnly>` tag, similar to the PageAccountsApproval page 

## **Visuals:**

Any visuals that are related to these changes

## **Requirements:**

- [ ] todo 1
- [ ] todo 2
- [ ] todo 3

## **External Factors:**

Describe any external requirements that might effect the issue (e.g need to await information from other party).

## **Related Issues/PRs:**

Link any other issue or PR that might be related to this issue.

## **Resources:**

Link any resources or people that might be helpful in the accomplishment of the issue.

### **Tutorials:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

### **Documentation:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

**Comment by natapokie** [comment]
no longer needed
