### ISSUE TITLE
Sponsor carousel component

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#84]
![image](https://user-images.githubusercontent.com/50821962/171288400-69656593-042d-46f7-9ed3-3be1304c5380.png)
See Figma
Should take an image component as argument and name of sponsor
Can use external carousel package (optional)
Make mobile friendly (only show 1 sponsor, with the other 2 offscreen)

**Comment by Cali0707** [comment]
Have an optional on-click function

**Comment by jameskokoska** [comment]
Would probably take a list of objects similar to
```js
{
  "name":"University of Toronto",
  "website":"www.google.ca",
  "backgroundColor" : "#FFFFFFF",
  "image" : require("UofTImage.png"),
}
```
